default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode

local: &local
  host: db
  username: postgres

development:
  <<: *default
  <<: *local
  database: rails_test_development

test:
  <<: *default
  <<: *local
  database: rails_test_test

production:
  <<: *default
  database: rails_test_production
  host: <%= ENV.fetch('DB_1_PORT_5432_TCP_ADDR', 'localhost') %>
  port: <%= ENV.fetch('DB_1_PORT_5432_TCP_PORT', '5432') %>
  username: postgres
